 export const omniMethod={
    listproperties:'omni_listproperties',
    getinfo:'omni_getinfo',
    getwalletbalances:"omni_getwalletbalances", 
    getwalletaddressbalances:"omni_getwalletaddressbalances",
    send:"omni_send", 
    gettransaction:"omni_gettransaction",
    listtransactions:"omni_listtransactions",
    gettradehistoryforpair:"omni_gettradehistoryforpair",
    gettradehistoryforaddress:"omni_gettradehistoryforaddress",
    sendissuancefixed:"omni_sendissuancefixed",
    sendissuancemanaged:"omni_sendissuancemanaged",
    getproperty:"omni_getproperty",
    sendchangeissuer:"omni_sendchangeissuer",
    sendgrant:"omni_sendgrant",
    sendrevoke:"omni_sendrevoke",
    sendissuancecrowdsale:"omni_sendissuancecrowdsale",
    getactivecrowdsales:"omni_getactivecrowdsales",
    getcrowdsale:"omni_getcrowdsale",
 }

